### ISSUE TITLE
Можно перевод мода Silent Gear?

### ISSUE THREAD

**Issue by grain12** [RushanM/Minecraft-Mods-Russian-Translation#35]
Вроде как русский язык в моде есть но он не работает (возможно устарел)

**Comment by RushanM** [comment]
Пока что есть другие приоритеты. Но я приму к сведению.

**Comment by RushanM** [comment]
В моде есть русский и он работает. Проверял на 1.20.1, скачивал [отсюда](https://modrinth.com/mod/silent-gear/versions?g=1.20.1&l=forge).

Возможно вы имели в виду какую-то другую версию мода?

Также попробуйте [альфа-версию русификатора для 1.20.x](https://github.com/RushanM/Minecraft-Mods-Russian-Translation/releases/download/a4/Rus-For-Mods-1.20-A4.zip) с модом, я добавил там перевод.
